---
ignored:
  # disable USER root
  - DL3002
  # disable pinning apk package versions
  - DL3018
  # disable following sourced files
  - SC1091
  # disable tag in base image -- hadolint doesn't like ARGS in FROM?
  - DL3006
