---
sudo: false
language: c
matrix:
  include:
    - &plumb
      env: TEST=markdownlint
      language: c
      services:
        - docker
      script: ./tests/mdl.sh

    - <<: *plumb
      env: TEST=yamllint
      script: ./tests/yamllint.sh

    - <<: *plumb
      env: TEST=shellcheck
      script: ./tests/shellcheck.sh

    - <<: *plumb
      env: TEST=hadolint
      script: ./tests/hadolint.sh

    - env: TEST=make
      script: ./tests/make.sh
branches:
  only:
    - master
    # also matched against tag pushes
    - /^\d+\.\d+\.\d+$/
notifications:
  email: false
